name: branvier
description: A Branvier project.
version: 0.9.90
homepage:

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: ">=1.16.1"

main: lib/branvier.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6

  #Extensions
  dartx: ^1.1.0 
  flutter_animate: ^4.1.1+1 

  #Core
  flutter_localizations:
    sdk: flutter
  flutter_modular:
  getx_lite: ^4.6.5
  mocktail: ^0.3.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter