name: branvier
description: A Branvier project.
version: 0.9.92
homepage:

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.16.1"

main: lib/branvier.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6

  #Core
  flutter_localizations:
    sdk: flutter
  flutter_modular:
  mocktail: ^0.3.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter